/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Fighting Force)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x801FBF00u
#define func_801FBF00 BootEntry  /* alias */
